language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.1
    - platform-tools
    - tools
    - extra-google-google_play_services

script:
  - ./gradlew test