language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.1
    - platform-tools
    - tools
    - extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-23

script:
  - ./gradlew test